# Generated by Django 3.2.7 on 2021-11-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stronaK', '0002_auto_20211120_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='oldknight',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['title']},
        ),
    ]
